### ISSUE TITLE
Crash in the challenge code for the depth chapter

### ISSUE THREAD

**Issue by rokonio** [sotrh/learn-wgpu#319]
The [challenge for the 8th chapter](https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial8-depth/src/challenge.rs)(on the depth buffer,) crashes on my pc:
```
❯ cargo run
   Compiling graphic_rust v0.1.0 (/home/rokonio/dev/rust/graphic_rust)
    Finished dev [unoptimized + debuginfo] target(s) in 5.90s
     Running `target/debug/graphic_rust`
[2022-02-17T16:45:54Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `Render Pipeline`
    error matching FRAGMENT shader requirements against the pipeline
    shader global ResourceBinding { group: 0, binding: 0 } is not available in the layout pipeline layout
    texture class Sampled { kind: Float, multi: false } doesn't match the shader Depth { multi: false }

', /home/rokonio/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

On a similar note, the informations given for the challenge are very thin and I think more details could be helpful. Also in the shader code, I noticed there isn't the code for the instancing from the previous chapter

**Comment by rokonio** [comment]
With the backtrace:
```
❯ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/graphic_rust`
[2022-02-17T17:01:18Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `Render Pipeline`
    error matching FRAGMENT shader requirements against the pipeline
    shader global ResourceBinding { group: 0, binding: 0 } is not available in the layout pipeline layout
    texture class Sampled { kind: Float, multi: false } doesn't match the shader Depth { multi: false }

', /home/rokonio/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: wgpu::backend::direct::default_error_handler
             at /home/rokonio/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
   3: core::ops::function::Fn::call
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:70:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1708:9
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at /home/rokonio/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2259:17
   6: wgpu::backend::direct::Context::handle_error
             at /home/rokonio/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:194:9
   7: <wgpu::backend::direct::Context as wgpu::Context>::device_create_render_pipeline
             at /home/rokonio/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:1314:13
   8: wgpu::Device::create_render_pipeline
             at /home/rokonio/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/lib.rs:1810:17
   9: graphic_rust::State::new::{{closure}}
             at ./src/main.rs:643:31
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  11: pollster::block_on
             at /home/rokonio/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.5/src/lib.rs:125:15
  12: graphic_rust::main
             at ./src/main.rs:821:21
  13: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sotrh** [comment]
> Also in the shader code, I noticed there isn't the code for the instancing from the previous chapter

The instancing code is still there. The challenge code for that chapter actually uses two sets of shaders: `shader.wgsl` for rendering the scene itself, and `challenge.wgsl` for rendering the depth texture to a quad.

As for your crash, I see too possible causes:

1. You're using `challenge.wgsl` in place of `shader.wgsl` when you create the main render pipeline that is used to draw the instanced scene.

2. The bind group layout you're using isn't configured correctly. The bind group layout for sampling a depth texture should look something like this:

```rust
let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
    label: Some("Depth Pass Layout"),
    entries: &[
        wgpu::BindGroupLayoutEntry {
            binding: 0,
            count: None,
            ty: wgpu::BindingType::Texture {
                sample_type: wgpu::TextureSampleType::Depth,
                multisampled: false,
                view_dimension: wgpu::TextureViewDimension::D2,
            },
            visibility: wgpu::ShaderStages::FRAGMENT,
        },
        wgpu::BindGroupLayoutEntry {
            binding: 1,
            count: None,
            ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Comparison),
            visibility: wgpu::ShaderStages::FRAGMENT,
        },
    ],
});
```

**Comment by rokonio** [comment]
Okay it makes sens now. I had only used the challenge.wgsl for the shader code.
