### ISSUE TITLE
Can't run tutorial examples from chapter 2

### ISSUE THREAD

**Issue by St0wy** [sotrh/learn-wgpu#461]
When trying to build any example from chapter 2 and onwards, they crash with this error message : 

```
thread 'main' panicked at 'called glDebugMessageCallback but it was not loaded.', C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\glow-0.12.0\src\gl46.rs:4234:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library\core\src\panicking.rs:64
   2: glow::gl46::go_panic_because_fn_not_loaded
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\glow-0.12.0\src\gl46.rs:4234
   3: glow::gl46::call_atomic_ptr_2arg
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\glow-0.12.0\src\gl46.rs:4316
   4: glow::gl46::struct_commands::GlFns::DebugMessageCallback
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\glow-0.12.0\src\gl46.rs:10203
   5: glow::native::impl$2::debug_message_callback<void (*)(u32,u32,u32,u32,ref$<str$>)>
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\glow-0.12.0\src\native.rs:2545
   6: wgpu_hal::gles::egl::impl$12::enumerate_adapters
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.15.1\src\gles\egl.rs:888
   7: wgpu_core::instance::impl$6::request_adapter::gather<wgpu_hal::gles::Api,tuple$<> >
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-core-0.15.0\src\instance.rs:733
   8: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::request_adapter<wgpu_core::hub::IdentityManagerFactory>
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-core-0.15.0\src\instance.rs:805
   9: wgpu::backend::direct::impl$7::instance_request_adapter
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.15.0\src\backend\direct.rs:576
  10: wgpu::context::impl$5::instance_request_adapter<wgpu::backend::direct::Context>
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.15.0\src\context.rs:1932
  11: wgpu::Instance::request_adapter
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.15.0\src\lib.rs:1424
  12: tutorial2_surface::impl$0::new::async_fn$0
             at .\code\beginner\tutorial2-surface\src\lib.rs:38
  13: tutorial2_surface::run::async_fn$0
             at .\code\beginner\tutorial2-surface\src\lib.rs:189
  14: pollster::block_on<enum2$<tutorial2_surface::run::async_fn_env$0> >
             at C:\Users\stowy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\pollster-0.2.5\src\lib.rs:125
  15: tutorial2_surface::main
             at .\code\beginner\tutorial2-surface\src\main.rs:4
  16: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\tutorial2-surface.exe` (exit code: 101)
```

I am on windows 11 with rustc 1.68.0. I run the example with this command : `RUST_BACKTRACE=1 cargo run --bin tutorial2-surface`

When following the tutorial on my own, I don't have this problem (and it seems like it's using Vulkan in my project instead of OpenGL).

**Comment by sotrh** [comment]
Can you share your code so I can see any minor differences?

**Comment by St0wy** [comment]
Here is my project when following the tutorial: https://github.com/St0wy/learn-wgpu
If you where asking about this repo, it was a fresh clone, so with nothing changed.

**Comment by sotrh** [comment]
So looking closer at the message it says it was trying to load `glDebugMessageCallback` but couldn't. This seems like a driver issue to me. Check that your graphics drivers are up to date.

**Comment by St0wy** [comment]
So I updated my graphics drivers and pulled the latest version and when running `cargo run --bin tutorial2-surface` I now have a Vulkan error instead of an OpenGL one, but the window still shows up.

This error prints in loop in the terminal :
```bash
[2023-08-02T13:22:02Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-04627 (0x45125641)]
        Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-04627 ] Object 0: handle = 0xab64de0000000020, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x45125641 | vkCmdBeginRenderPass: Image view #0 created from an image with usage set as (VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT) but using VkImageViewUsageCreateInfo the inherited usage is the subset (VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT) and the image info #0 used to create the framebuffer had usage set as (VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT). The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView with an inherited usage equal to the usage member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://vulkan.lunarg.com/doc/view/1.3.243.0/windows/1.3-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-04627)
[2023-08-02T13:22:02Z ERROR wgpu_hal::vulkan::instance]         objects: (type: RENDER_PASS, hndl: 0xab64de0000000020, name: ?)
```

**Comment by sotrh** [comment]
It's complaining that the surface texture is just bound as a color attachment and not setup for transfer. We don't have access for `VK_IMAGE_USAGE_TRANSEr_SRC_BIT` so it's either a driver problem, or it's  a bug with WGPU.

**Comment by St0wy** [comment]
The computer where I did these tests died recently in a loop of BSOD, all with a video related error code. Maybe at that time the GPU was already malfunctionning a bit and caused these issues. I wanted to try the latest version on my current machine to see if I still have the bug, but now I can't compile it because of `value-bag`.

I guess this issue could be closed since it was probably just a problem with my old computer.

**Comment by sotrh** [comment]
Ok, I'll close this for now then. If you run into this issue again feel free to re-open this.
