### ISSUE TITLE
Configuration fix for wasm

### ISSUE THREAD

**Issue by pasimko** [sotrh/learn-wgpu#587]
I'm on Mozilla Firefox 133.0.3, and had to deviate from
https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial1-window/src/lib.rs in a couple places to get wasm working.
Everything ran natively, but running in browser logged
`panicked at /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:805:14:
Surface was not configured?`. 
I added the following lines:
```rs
#[cfg(target_arch="wasm32")]
surface.configure(&device, &config);
```

Which brought me to 
```
Panicked at /home/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:786:18:
Error in Surface::configure: Validation Error

Caused by:
  Both `Surface` width and height must be non-zero. Wait to recreate the `Surface` until the window has non-zero area.
```
Which was fixed with:
```rs
#[cfg(not(target_arch="wasm32"))]
let size = window.inner_size();
#[cfg(target_arch="wasm32")]
let size = PhysicalSize {width: 100, height: 100};
```

There's probably a better way to prevent these errors, but I figured I'd raise an issue to help others who might run into the same thing. Is there a better workaround for this?

**Comment by pasimko** [comment]
Ah, I see that if I had looked closer at the provided code I would have seen that you resolved this in https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial2-surface/src/lib.rs. Might be worth mentioning in the main article that
```rs
if !surface_configured {
    return;
}
``` comes from the main file?
